// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Rally the Righteous
 * {1}{R}{W}
 * Instant
 * Radiance — Untap target creature and each other creature that shares a color with it. Those creatures get +2/+0 until end of turn.
 */
val RallyTheRighteous = card("Rally the Righteous") {
    manaCost = "{1}{R}{W}"
    colorIdentity = "WR"
    typeLine = "Instant"
    oracleText = "Radiance — Untap target creature and each other creature that shares a color with it. Those creatures get +2/+0 until end of turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature, excludeSelf = true),
                Effects.Untap(EffectTarget.Self)
            ),
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Permanent, excludeSelf = true),
                Effects.ModifyStats(2, 0, EffectTarget.Self)
            )
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "222"
        artist = "Dan Murayama Scott"
        flavorText = "Yuri took up the ragged Boros banner, and his brethren, inspired by the act, followed him back into the fight."
        imageUri = "https://cards.scryfall.io/normal/front/9/d/9da51b6c-2e27-4b41-8fb0-bd9f6ad47b19.jpg"
    }
}
