// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Trophy Hunter
 * {2}{G}
 * Creature — Human Archer
 * 2/3
 * {1}{G}: This creature deals 1 damage to target creature with flying.
 * Whenever a creature with flying dealt damage by this creature this turn dies, put a +1/+1 counter on this creature.
 */
val TrophyHunter = card("Trophy Hunter") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Human Archer"
    oracleText = "{1}{G}: This creature deals 1 damage to target creature with flying.\nWhenever a creature with flying dealt damage by this creature this turn dies, put a +1/+1 counter on this creature."
    power = 2
    toughness = 3
    activatedAbility {
        cost = Costs.Mana("{1}{G}")
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = DealDamageEffect(1, t)
    }
    triggeredAbility {
        trigger = Triggers.Dies
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "187"
        artist = "rk post"
        imageUri = "https://cards.scryfall.io/normal/front/f/1/f18d1047-9010-437c-94ab-7a8ad3a0250f.jpg"
    }
}
