// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Wojek Embermage
 * {3}{R}
 * Creature — Human Wizard
 * 1/2
 * Radiance — {T}: This creature deals 1 damage to target creature and each other creature that shares a color with it.
 */
val WojekEmbermage = card("Wojek Embermage") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Human Wizard"
    oracleText = "Radiance — {T}: This creature deals 1 damage to target creature and each other creature that shares a color with it."
    power = 1
    toughness = 2
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature, excludeSelf = true),
            DealDamageEffect(1, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "152"
        artist = "Luca Zontini"
        flavorText = "\"Your brother's crimes are your crimes. You stood by and lent support, so you too must face judgment.\""
        imageUri = "https://cards.scryfall.io/normal/front/e/1/e1614866-fb0b-47bd-ab26-5c20ff175d10.jpg"
    }
}
