// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Wojek Siren
 * {W}
 * Instant
 * Radiance — Target creature and each other creature that shares a color with it get +1/+1 until end of turn.
 */
val WojekSiren = card("Wojek Siren") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Radiance — Target creature and each other creature that shares a color with it get +1/+1 until end of turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature, excludeSelf = true),
            Effects.ModifyStats(1, 1, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "37"
        artist = "Zoltan Boros & Gabor Szikszai"
        flavorText = "It is the call to arms, the call to fury, the call to blood."
        imageUri = "https://cards.scryfall.io/normal/front/a/5/a55c0d7d-2325-4d7e-b449-c8fdcf988ec0.jpg"
    }
}
